### ISSUE TITLE
Chrome v108 support

### ISSUE THREAD

**Issue by myartsev** [lwthiker/curl-impersonate#129]
Not sure what (if anything) is needed to add support for Chrome 108 (latest version as of 30/12/2022)

**Comment by myartsev** [comment]
Pull requests welcome?
Haven't dug into it too much, but it looks relatively easy to add support (as well as adding a Linux OS to the compatibility matrix).

**Comment by lwthiker** [comment]
Pull requests are welcome. In order to add support for a new browser you'd have to:

1. Actually verify that the signature matches. This means inspecting the TLS client hello and the HTTP headers.
2. First open a pull request with the changes to curl in this repository: https://github.com/lwthiker/curl. The latest curl-impersonate code is tracked in the `impersonate-chrome` branch.
3. Create the patch files needed for this repository along with the additional scripts.

You can take a look at #123

**Comment by myartsev** [comment]
Got it, thank you!
As far as I can tell, there haven't been any significant differences with Chrome v108 (unlike your last update to v107) aside from the updated user agent strings.

I'm opting to just call `curl-impersonate-chrome` directly and pass in all the headers.

**Comment by A-Posthuman** [comment]
I've also been using just chrome 108 headers with the older curl-impersonate 107 support, seemed to work well for me.

I see now chrome 109 has just been released, has anyone had a look at that yet?

**Comment by A-Posthuman** [comment]
I compared chrome 109 to curl-impersonate 107 and they seem to still have the same JA3 fingerprint according to this API:

https://tls.peet.ws/api/all

**Comment by myartsev** [comment]
Closing, no action item here
