### ISSUE TITLE
"curl-impersonate-chrome: No such file or directory" (but the file exists)

### ISSUE THREAD

**Issue by izzues** [lwthiker/curl-impersonate#78]
Hey,

I downloaded the binaries from the Releases page. It works on Debian, but on NixOS I'm getting the following error:

    $ ./curl_chrome99
    # [...]/curl_chrome99: line 10: [...]/curl-impersonate-chrome: No such file or directory

When I run `ldd [...]/curl-impersonate-chrome`, this is what I see:

        linux-vdso.so.1 (0x00007ffe85ba6000)
        libz.so.1 => not found
        libpthread.so.0 => /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libpthread.so.0 (0x00007f03352ed000)
        libc.so.6 => /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib/libc.so.6 (0x00007f03350ef000)
        /lib64/ld-linux-x86-64.so.2 => /nix/store/f6kvkdzp6qfjm6h94d0jgfvm4r06xcaq-glibc-2.34-210/lib64/ld-linux-x86-64.so.2 (0x00007f0335606000)

Unsure if related: I see a test is performed in the build script, but it's not checking for zlib? In addition, I don't think it works as expected (if I'm not mistaken, `grep -q` returns success if _any_ of the patterns is found):

https://github.com/lwthiker/curl-impersonate/blob/1b46a3fb88f92ae95b1374d1c3fbdf433002cad0/firefox/Dockerfile.alpine#L94

**Comment by lwthiker** [comment]
Hi,

>     libz.so.1 => not found

It seems like you are missing `libz.so.1` (zlib). Have you tried installing it?

>  I see a test is performed in the build script, but it's not checking for zlib?

The test checks that certain libraries were compiled statically into curl-impersonate. I added it because sometimes the linker would insist on linking things dynamically. zlib specifically is not meant to be compiled statically into curl-impersonate since it is ubiquitous on most Linux systems.

About the correctness of the test itself, `grep` will return success if any of the static libraries was accidentally linked dynamically, and therefore the result is negated with `!` (we want the build to fail in that case).
